version: '2'
services:
  db:
    image: postgres
    hostname: db
    domainname: project.local
  web:
    build: cont2/.
    command: python manage.py runserver 0.0.0.0:8000
    hostname: server
    domainname: project.local
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
  client:
    build: cont3/.
    hostname: client
    domainname: project.local
    depends_on:
      - web
